### PR TITLE
fix: Replace SurfaceHeightFacet with SurfacesFacet and ElevationFacet

### PR DESCRIPTION
**Pull request by 4Denthusiast**
Update for engine PR https://github.com/MovingBlocks/Terasology/pull/4237. Mostly actually use ElevationFacet, rather than SurfacesFacet, even for buildings, for which the SurfacesFacet would technically be more appropriate, because the assumption of a 2D height-map is quite strongly baked in. Although this PR may not fully take advantage of the change, it at least should make the module compatible with it.

### CODE REVIEW

**Review by skaldarnar — CHANGES_REQUESTED** [review]
I cannot create a Static Cities world because of the following error:
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.terasology.world.block.BlockManager.getBlock(org.terasology.world.block.BlockUri)" because "blockManager" is null
        at org.terasology.staticCities.BlockTheme$Builder.<init>(BlockTheme.java:116)
        at org.terasology.staticCities.BlockTheme$Builder.<init>(BlockTheme.java:105)
        at org.terasology.staticCities.BlockTheme.builder(BlockTheme.java:54)
        at org.terasology.staticCities.CityWorldGenerator.createWorld(CityWorldGenerator.java:94)
        at org.terasology.world.generation.BaseFacetedWorldGenerator.getWorldBuilder(BaseFacetedWorldGenerator.java:101)
        at org.terasology.world.generation.BaseFacetedWorldGenerator.setWorldSeed(BaseFacetedWorldGenerator.java:57)
        at org.terasology.rendering.nui.layers.mainMenu.WorldPreGenerationScreen.setWorldGenerators(WorldPreGenerationScreen.java:300)
        at org.terasology.rendering.nui.layers.mainMenu.WorldPreGenerationScreen.setEnvironment(WorldPreGenerationScreen.java:101)
        at org.terasology.rendering.nui.layers.mainMenu.UniverseSetupScreen.lambda$initialise$4(UniverseSetupScreen.java:226)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
```

**Comment by jdrueckert** [comment]
> 
> 
> I cannot create a Static Cities world because of the following error:
> 
> ```
> Caused by: java.lang.NullPointerException: Cannot invoke "org.terasology.world.block.BlockManager.getBlock(org.terasology.world.block.BlockUri)" because "blockManager" is null
>         at org.terasology.staticCities.BlockTheme$Builder.<init>(BlockTheme.java:116)
>         at org.terasology.staticCities.BlockTheme$Builder.<init>(BlockTheme.java:105)
>         at org.terasology.staticCities.BlockTheme.builder(BlockTheme.java:54)
>         at org.terasology.staticCities.CityWorldGenerator.createWorld(CityWorldGenerator.java:94)
>         at org.terasology.world.generation.BaseFacetedWorldGenerator.getWorldBuilder(BaseFacetedWorldGenerator.java:101)
>         at org.terasology.world.generation.BaseFacetedWorldGenerator.setWorldSeed(BaseFacetedWorldGenerator.java:57)
>         at org.terasology.rendering.nui.layers.mainMenu.WorldPreGenerationScreen.setWorldGenerators(WorldPreGenerationScreen.java:300)
>         at org.terasology.rendering.nui.layers.mainMenu.WorldPreGenerationScreen.setEnvironment(WorldPreGenerationScreen.java:101)
>         at org.terasology.rendering.nui.layers.mainMenu.UniverseSetupScreen.lambda$initialise$4(UniverseSetupScreen.java:226)
>         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> ```

I recall that we saw (and fixed or at least worked around?) that in LaS already some time ago... the issue is that the block theme stuff is called before the block manager exists (and then later it's called and in the meantime the block manager is present) and IIRC we did something so that the block theme stuff is not called at that first time but only later at that second time... unfortunately I don't recall further details.

**Review by skaldarnar — APPROVED** [review]
See https://github.com/Terasology/StaticCities/issues/6

Changes look reasonable.

**Comment by skaldarnar** [comment]
Just for the record: the only way to start StaticCities at the moment is via a headless server (because it is impossible to start via the AGS). I've use the following `override.cfg`:

```json
{
  "defaultModSelection": {
    "modules": [
      "CoreSampleGameplay",
      "StaticCities"
    ],
    "defaultGameplayModuleName": "CoreSampleGameplay"
  },
  "worldGeneration": {
    "defaultGenerator": "StaticCities:staticCities"
  }
}

```

World loads fine! The fences around the buildings are floating in the air, and the base layer of buildings in on top of the surface. Looks like an off-by-one error with the elevation facet data (usage within the city generator code).

Terasology-201127201800-1280x800

**Pull request merged**
